# Generated by Django 5.0 on 2026-01-12 03:49

import apps.core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID unik karyawan, contoh: EMP0001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Alamat email karyawan (harus domain perusahaan)",
                        max_length=254,
                        unique=True,
                        validators=[apps.core.validators.validate_email_domain],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Nomor telepon karyawan (08xxx atau 62xxx)",
                        max_length=15,
                        validators=[apps.core.validators.validate_phone_number],
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True,
                        help_text="Tanggal mulai bekerja (opsional)",
                        null=True,
                    ),
                ),
                (
                    "type_of_employment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        help_text="Jenis kepegawaian (full time, kontrak, magang, dll)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Status kepegawaian (aktif, cuti, resign, dll)",
                        max_length=20,
                    ),
                ),
                (
                    "face_photo_front",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak depan (opsional)",
                        null=True,
                        upload_to="faces/front/%Y/%m/",
                    ),
                ),
                (
                    "face_photo_left",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak kiri (opsional)",
                        null=True,
                        upload_to="faces/left/%Y/%m/",
                    ),
                ),
                (
                    "face_photo_right",
                    models.ImageField(
                        blank=True,
                        help_text="Foto wajah tampak kanan (opsional)",
                        null=True,
                        upload_to="faces/right/%Y/%m/",
                    ),
                ),
                (
                    "face_encoding",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        help_text="Data encoding wajah untuk face recognition (otomatis)",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Waktu data dihapus (soft delete)",
                        null=True,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User yang menghapus data ini (soft delete)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["employee_id"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nama divisi (HR Department, HR Manager, HR Recruitment)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Kode unik divisi (HR, HR-MGR, HR-RECRUIT)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Deskripsi divisi"),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Hierarchy level (0=top, 1=sub, 2=child, dst)",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent division (kosong jika top level)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
                "db_table": "divisions",
                "ordering": ["level", "code"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Divisi/Departemen organisasi (opsional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="accounts.division",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nama jabatan (Staff, Supervisor, Manager, HR, CEO)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Kode jabatan (STF, SPV, MGR, HR, CEO)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Semakin besar, semakin tinggi jabatan"
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Django Groups (hak akses) untuk jabatan ini",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position",
                        to="auth.group",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Atasan langsung (opsional, untuk navigasi hirarki)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subordinates",
                        to="accounts.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "positions",
                "ordering": ["level"],
                "unique_together": {("level", "code")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Jabatan/posisi pekerjaan (bisa multiple roles)",
                related_name="employees",
                to="accounts.position",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["employee_id"], name="users_employe_55e465_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["status", "is_active"], name="users_status_1462fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["division", "is_active"], name="users_divisio_71338d_idx"
            ),
        ),
    ]
