# Generated by Django 5.0 on 2026-01-07 09:14

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nama jabatan (Staff, Supervisor, Manager, HR, CEO)",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Kode jabatan (STF, SPV, MGR, HR, CEO)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        db_index=True, help_text="Semakin besar, semakin tinggi jabatan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "positions",
                "ordering": ["level"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["employee_id"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_employe_55e465_idx",
            old_name="idx_employee_id",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_status_1462fc_idx",
            old_name="idx_status_active",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_divisio_71338d_idx",
            old_name="idx_division_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Waktu data dihapus (soft delete)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User yang menghapus data ini (soft delete)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="Divisi/Departemen organisasi (opsional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="accounts.division",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Alamat email karyawan (harus domain perusahaan)",
                max_length=254,
                unique=True,
                validators=[apps.core.validators.validate_email_domain],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                db_index=True,
                help_text="ID unik karyawan, contoh: EMP0001",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_encoding",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Data encoding wajah untuk face recognition (otomatis)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_photo_front",
            field=models.ImageField(
                blank=True,
                help_text="Foto wajah tampak depan (opsional)",
                null=True,
                upload_to="faces/front/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_photo_left",
            field=models.ImageField(
                blank=True,
                help_text="Foto wajah tampak kiri (opsional)",
                null=True,
                upload_to="faces/left/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="face_photo_right",
            field=models.ImageField(
                blank=True,
                help_text="Foto wajah tampak kanan (opsional)",
                null=True,
                upload_to="faces/right/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hire_date",
            field=models.DateField(
                blank=True, help_text="Tanggal mulai bekerja (opsional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("on_leave", "On Leave"),
                    ("terminated", "Terminated"),
                ],
                db_index=True,
                default="active",
                help_text="Status kepegawaian (aktif, cuti, resign, dll)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type_of_employment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                ],
                help_text="Jenis kepegawaian (full time, kontrak, magang, dll)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="group",
            field=models.OneToOneField(
                blank=True,
                help_text="Django Groups (hak akses) untuk jabatan ini",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Atasan langsung (opsional, untuk navigasi hirarki)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subordinates",
                to="accounts.position",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Jabatan/posisi pekerjaan (opsional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="accounts.position",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("level", "code")},
        ),
    ]
