# Generated by Django 5.0 on 2026-01-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_position_alter_user_options_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.AddField(
            model_name="user",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Jabatan/posisi pekerjaan (bisa multiple roles)",
                null=True,
                related_name="employees",
                to="accounts.position",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="group",
            field=models.OneToOneField(
                blank=True,
                help_text="Django Groups (hak akses) untuk jabatan ini",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position",
                to="auth.group",
            ),
        ),
    ]
