# Generated by Django 5.0 on 2026-01-08 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_position_user_positions_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="group",
            field=models.OneToOneField(
                blank=True,
                help_text="Django Groups (hak akses) untuk jabatan ini",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position",
                to="auth.group",
            ),
        ),
    ]
