# Generated by Django 5.0 on 2026-01-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Core Permission",
                "verbose_name_plural": "Core Permissions",
                "permissions": [
                    ("view_company_dashboard", "Can view company-wide dashboard"),
                    ("view_division_dashboard", "Can view division dashboard"),
                    ("view_own_dashboard", "Can view own dashboard"),
                    ("export_dashboard_data", "Can export dashboard data"),
                    ("approve_attendance", "Can approve attendance"),
                    ("view_all_attendance_report", "Can view all attendance reports"),
                    ("approve_all_leaves", "Can approve all leaves"),
                    ("reject_leave", "Can reject leave"),
                    ("cancel_approved_leave", "Can cancel approved leave"),
                    ("export_attendance_report", "Can export attendance report"),
                    ("export_leave_report", "Can export leave report"),
                    ("export_payroll_report", "Can export payroll report"),
                    ("view_analytics", "Can view analytics dashboard"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="AppPermission",
        ),
    ]
